config/routes.rb
Coupan::Application.routes.draw do

  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      :registrations => "registrations"
    }

  root 'home#index'
  resources :brands, only: [:index, :show] do
    resources :coupons, only: [:index]
  end

  resources :coupons # index is legacy url (for above brand_coupon)

  resources :release_notes, only: [:index] do
    collection do
      get 'recent'
    end
  end

  resources :notifications, only: [:index] do
    collection do
      get 'recent'
    end
  end

  get '/brands/:brand_id/users/:id/coupons', to: 'coupons#me', as: 'brand_user_coupons'
  get '/users/:id/coupons', to: 'coupons#me', as: 'user_coupons' # legacy url(for above)

  get '/users/:id/coupons/:tibu_tibu_id/', to: 'coupons#recommend', as: 'recommend_coupons'
  post '/users/:id/coupons/post_kakao_story', to: 'coupons#post_kakao_story', as: 'post_kakao_story'
  get '/users/:id/coupons/:tibu_tibu_id/request_exchange', to: 'coupons#request_exchange', as: 'request_exchange_coupon'

  get '/oauth/', to: 'home#oauth_redirect'

  resource :api do
    member do
      get 'stores'
      get 'companies'
      get '/cities/:province_id/', to: 'apis#cities'
    end
  end

  get '/googlec41459c75d69b2af.html', to: 'home#google_valification'

  resources :coupons

end

app/models/coupon.rb
# 164,1512,3698,155,3556,
# 3104
class Coupon < ActiveRecord::Base

  belongs_to :user
  belongs_to :tibu_tibu
  belongs_to :brand

  validates_uniqueness_of :user_id, scope: :tibu_tibu_id


  def recommend
  end

  def self.check_status(user_id)
    # stores = {}
    # for (store_id, user_with_scores) in Coupon.recommend(1, receive_coupon_ids)
    #   stores[store_id] = !user_with_scores.empty?
    # end
    # stores
    coupons = Coupon.where(user_id: user_id)
    stores = {}
    for my_coupon in coupons
      stores[my_coupon.store_id] =
        Coupon.where(store_id: my_coupon.store_id)
        .where("stamp >= ?", my_coupon.store.max_stamp - my_coupon.stamp).count == 0 ? false : true
    end
    stores
  end

  def image_path
    if self.picture
      self.picture
    else
      if self.tibu_tibu.brand_id == 1
        url = 'ssyls/' + self.tibu_tibu.brand_id.to_s + '/' + self.tibu_tibu.num.to_s + '.jpg'
        ActionController::Base.helpers.asset_path(url)
      else
        nil
      end
    end
  end

end

app/controllers/coupons_controller.rb
require 'RMagick'
require 'rest_client'

class CouponsController < ApplicationController
  include Magick

  skip_before_action :authenticate_user!, only: [:index, :me, :show]

  before_action :tibutibus, only: [:index, :me]


  def index
    # legacy support (kakao friends coupon links)
    redirect_to brand_coupons_path(1) and return if params.fetch(:brand_id, nil).nil?

    query = params[:q]
    @users = User.joins(:coupons)
      .where(coupons: { brand_id: @brand.id })
      .group("users.id")
      .select("users.*")
      .select("COUNT(coupons.id) as c_count")
      .select("COUNT(coupons.picture) as p_count")
      .order("p_count desc", "c_count desc")

    @legend_users = @users.
      having("COUNT(coupons.picture) = ?", @brand.max_coupon_count)

    @users = @users.
      having("COUNT(coupons.picture) < ?", @brand.max_coupon_count).
      order("p_count desc", "c_count desc")

    if query
      if query == 'l'
        my_location = current_user.cities.pluck(:id)
        @users = @users.joins(:cities).where('cities.id in (?)', my_location)
      elsif query == 'g'
        @users = @users.where(company: current_user.company_id)
      end
    end

    @whole_ssyl_count = TibuTibu.where(brand_id: @brand.id).count
    @users = @users.page(params[:page]).per(15)

    if request.xhr?
      return render 'coupons/_list', layout: false
    end

  end

  def destroy
    coupon = Coupon.find params[:id]
    coupon.destroy! if current_user == coupon.user

    redirect_to user_coupons_path(current_user)
  end

  def show
    @coupon = Coupon.find params[:id]
    @recommend_coupons = @coupon.recommend
  end

  def edit
    @coupon = Coupon.find params[:id]
    render layout: false
  end

  def update
    @coupon = Coupon.find params[:id]

    if params[:coupon][:picture]
      path = "/picture/ssyls/#{self.current_user.id}/"
      if !File.directory?("public" + path)
        Dir.mkdir("public" + path)
      end

      temp_image = params[:coupon][:picture]
      image = Magick::Image.from_blob(temp_image.read).last
      image = image.resize_to_fill(150, 200)
      path = path + 'ssyl-' + SecureRandom.uuid + "." + image.format
      image.write("public" + path) do self.quality = 60 end
      @coupon.update(picture: path)
    end

    prev_count = @coupon.count
    count = params[:coupon][:count].to_i
    if current_user == @coupon.user
      if count == 0
        @coupon.destroy
      else
        @coupon.update(count: count)
      end

      if prev_count == 1 and count == 2
        _citizen = current_user.citizen.where(location_notification: true)
        had_citizen = _citizen
          .eager_load(:coupons)
          .where("coupons.tibu_tibu_id = ?", @coupon.tibu_tibu_id)
          .where("coupons.brand_id = ?", @coupon.brand_id)
        citizen = _citizen.pluck(:id) - had_citizen.pluck(:id)

        _colleague = current_user.colleague.where(group_notification: true)
        had_colleague = _colleague
          .eager_load(:coupons)
          .where("coupons.tibu_tibu_id = ?", @coupon.tibu_tibu_id)
          .where("coupons.brand_id = ?", @coupon.brand_id)
        colleague = _colleague.pluck(:id) - had_colleague.pluck(:id)

        notifier = (citizen + colleague).uniq
        queries = notifier.map do |receiver|
          Notification.new({
            sender_id: current_user.id,
            tibu_tibu_id: @coupon.tibu_tibu_id,
            receiver_id: receiver
          })
        end

        Notification.import(queries)
      end
    end

    render json: { coupon: @coupon }
  end

  def new
  end

  def create
    coupon = Coupon.new(coupon_params)
    if coupon.save
      if request.xhr?
        @user = current_user
        return render partial: 'coupons/me/active_ssyl', locals: {coupon: coupon, has_ssyl: true }
      else
        return redirect_to user_coupons_path current_user
      end
    end

    render 'coupon/new'
  end


  def me
    # legacy support (kakao friends coupon links)
    redirect_to brands_path and return if params.fetch(:brand_id, nil).nil?

    @user = User.find params[:id]
    @user_coupons = @user.coupons.where(brand: @brand)
    @user_ssyl_ids = @user_coupons.pluck(:tibu_tibu_id)

    if current_user
      @my_ssyl_ids = current_user.coupons.pluck(:tibu_tibu_id)
    end
  end

  def recommend
    @user = User.find params[:id]

    if @user == current_user
      @tibutibu = TibuTibu.find(params[:tibu_tibu_id])
      @recommend_coupons = @tibutibu.has_many_coupons
    else
      coupons = Coupon.find_by(
        tibu_tibu_id: params[:tibu_tibu_id],
        user_id: params[:id]
      )
    end

    render layout: false
  end

  def request_exchange
    @user = User.find params[:id]
    @coupon = Coupon.find_by(
      tibu_tibu_id: params[:tibu_tibu_id],
      user_id: params[:id]
    )
    @candidate_coupons = @user.recommended_coupons_with(current_user)

    render layout: false
  end

  def post_kakao_story
    current_user.token_refresh if current_user.token_expired?

    link = Rails.application.routes.url_helpers.user_coupons_url(
      current_user.id, host: request.host_with_port)

    result = RestClient.post(
      "https://kapi.kakao.com/v1/api/story/post/note",
      "content=#{params[:content]}\n\n#{link}",
      "Authorization" => "Bearer #{current_user.token}"
    )

    if result['id']
      return render json: result
    else
      return render json: {}, status: 500
    end
  end


  private def tibutibus
    @tibutibus = TibuTibu.where(brand: @brand)
  end

  private def coupon_params
    user = current_user
    params.require(:coupon).permit(:tibu_tibu_id).merge(user: user, brand: @brand)
  end

end

app/helpers/coupon_helper.rb
module CouponHelper
  def exchangerble_ssyls(coupons, user)
    html = "<ul class='list-unstyled list-inline'>"
    coupons.each do |coupon|
      html += "<li class='ssyl' style='background-image:url(#{coupon.image_path});'></li>"
    end
    html += "</ul>"

    if user.phone_number.present? or user.kakao_id.present? or user.user_cities.present?
      html += "<ul class='contact'>"
      if user.phone_number.present?
        html += "<li><label>연락처 :</label><a class='btn btn-link' href='tel:+#{user.phone_number}'>#{user.phone_number}</a></li>"
      end
      if user.kakao_id.present?
        html += "<li><label>KAKAO ID :</label><a class='btn btn-link'>#{user.kakao_id}</a></li>"
      end
      if user.user_cities.present?
        html += "<li><label>장소 :</label> #{user.cities_name}</li>"
      end
      html +="</ul>"
    end
    html
  end
end

app/views/coupons/_append_stamp_modal.html.haml
#appendStampModal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ type: "button", data: {dismiss: "modal"} }
          %span &times;
          %span.sr-only Close
        %h4 최대 스탬프는 몇 개인가요?
      .modal-body
        %input.dial{ name: "coupon[max_stamp]", type: "text",  value: "10", data: { min: 5, max: 25 } }
      .modal-footer
        %button.btn.btn-primary.change-maximum-stamp{ type: "button", data: {dismiss: "modal"}} 변경
        %button.btn.btn-default{ type: "button", data: {dismiss: "modal"}} 취소

app/views/coupons/_list.html.haml
- @users.each_with_index do |user, index|
  %h4.hidden= "#{user.name}님은 현재까지 #{user.p_count}의 인증사진과 #{user.c_count}의 띠부띠부씰을 수집했습니다. 완료까지 #{@whole_ssyl_count - user.c_count}개가 남았습니다."
  .portfolio-sec.media{ class: "#{ 'rank-' + index.to_s if index < 3 and !params[:page]}" }
    - if index < 3 and !params[:page]
      .rank-tag
        = index + 1
    = link_to brand_user_coupons_path(@brand, user), class: "pull-left" do
      %img.media-object.profile-image{ src: "#{user.image}" }

    = link_to brand_user_coupons_path(@brand, user), class: "media-body" do
      %h4.media-heading
        %span= "#{(user.name.present? ? user.name : "NONAME")}"
        %span.pull-right= user.last_created_coupon(@brand.id).updated_at.strftime('%m. %d')
      .clearfix
      %div
        %button.btn-default.ssyl.ssyl-sm.confirm Pic.
        %span.glyphicon.glyphicon-remove
        %span= user.p_count

        %button.btn-default.ssyl.ssyl-sm.active Get
        %span.glyphicon.glyphicon-remove
        %span= user.c_count

        %button.btn-default.ssyl.ssyl-sm Miss
        %span.glyphicon.glyphicon-remove
        %span= @whole_ssyl_count - user.c_count

= link_to_next_page @users, '다음 페이지 보기'

app/views/coupons/_regend_list.html.haml
- if @legend_users.present?
  #legends.portfolio-sec
    .portfolio-desc.text-center
      - @legend_users.each_with_index do |user, index|
        = link_to user_coupons_path(user), class: 'pull-left' do
          %img.media-object.profile-image{ src: "#{user.image}" }
      .clearfix
      .btn.theme-btn-default.btn-lg 벌써 다 모았네요!!

app/views/coupons/_story_post_modal.html.haml
= form_tag(post_kakao_story_path, authenticity_token: true, id: "post-kakao-story", class: "modal fade", remote: true ) do
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ type: :button, data: { dismiss: "modal" } }
          %span{ aria: { hidden: "true" } } &times;
        %h4.modal-title 카카오 스토리에 포스팅하기
      .modal-body
        .media
          %a.pull-left
            %img{ src: @user.image}

          .media-body
            %textarea{ name: 'content', rows: 10, placeholder: "공유할 내용을 적어주세요!" }
            %span.link-help 아래 링크가 같이 공유되요.
            .link
              %p= "#{request.protocol}#{request.host_with_port}#{request.fullpath}"

      .modal-footer
        .text-center
          %button.btn.btn-default{ type: :button, data: { dismiss: "modal" } } 닫기
          %button.btn.btn-primary{ type: :submit } 포스팅

app/views/coupons/edit.html.haml
.modal-header
  %button.close{type: "button", data: { dismiss: "modal" }}
    %span &times;
    %span.sr-only Close
  %h4.modal-title 씰 업데이트하기
.modal-body
  = form_for @coupon, multipart: true, url: {action: "update"}, html: {class: "text-center update-ssyl"} do |f|
    = f.hidden_field :count

    %h4 갯수가 변경되었어요!
    %button.btn.btn-link.btn-lg.minus
      .glyphicon.glyphicon-minus
    %span#counter= @coupon.count
    %button.btn.btn-link.btn-lg.plus
      .glyphicon.glyphicon-plus
    .space-10.text-center.small.text-info
      %span "+, -"를 클릭하면 자동으로 업데이트 되요.

    #confirm-picture
      %h4 인증사진을 올려볼까요?
      .text-center.text-danger.small 핸드폰으로 사진찍을 때는 홈버튼을 오른쪽으로 해주세요.
      .space-10
      .row
        .col-xs-offset-3.col-xs-6.col-xs-offset-3
          .ssyl{style: "background-image:url(#{@coupon.image_path});"}

          = f.file_field :picture, class: "hidden"
          %label.btn.btn-block.btn-main{ for: "coupon_picture" } 사진 올리기

.modal-footer
  .text-center
    = button_to "쿠폰을 삭제할께요!", coupon_path, method: :delete, class: "btn btn-danger", data: { confirm: "정말로 삭제할꺼예요?" } 

app/views/coupons/index.html.haml
- content_for :title do
  = "띠부띠부 - 씰 모음 순위"

- content_for :meta do
  %meta{content: "띠부띠부 모음 순위 - 현재까지 씰을 모두 모은 사용자는 #{@legend_users.size if @legend_users.present?}명입니다.", name: "description"}
  %meta{content: "띠부띠부, 카카오프렌즈, 씰, 교환, 순위, TibuTibu", name: "keyword"}


.hidden
  - if @legend_users.present?
    %h3= "현재까지 #{@legend_users.size}명의 사용자가 카카오프렌즈 띠부띠부 씰을 다 모았습니다!!"
    %ul
      - @legend_users.each_with_index do |user, index|
        %li= user.name
  - if @users.present?
    %h3= "현재 실시간 띠부띠부 랭킹입니다."
    %ul
      - @users.each_with_index do |user, index|
        %li= user.name


.row
  - if current_user
    #coupon-toggle.col-xs-12.btn-group.btn-group-justified{ data: { toggle: "buttons" } }
      %label.btn.btn-default{ class: "#{ 'btn-primary active' unless params[:q] }"}
        %input{ type: "radio", data: {href: brand_coupons_path(@brand)} } 전체보기
      %label.btn.btn-default{ class: "#{ 'btn-primary active' if params[:q] == 'l' }"}
        %input{ type: "radio", data: {href: "#{brand_coupons_path(@brand)}?q=l"} } 우리동네보기

      %label.btn.btn-default{ class: "#{ 'btn-primary active' if params[:q] == 'g' }"}
        %input{ type: "radio", data: {href: "#{brand_coupons_path(@brand)}?q=g"} } 우리그룹보기


  #coupon-list.col-xs-12
    - if current_user and params[:q] == 'l' and not current_user.cities.exists?
      .alert.alert-warning
        %strong 아이쿠!
        %p 씰을 교환할 수 있는 장소를 지정하지 않았네요.
        %a{ href: edit_user_registration_path } 장소 추가하러 가기!
    - elsif current_user and params[:q] == 'g' and not current_user.company_id.present?
      .alert.alert-warning
        %strong 아이쿠!
        %p 내가 속한 그룹을 지정하지 않았네요.
        %a{ href: edit_user_registration_path } 그룹 추가하러 가기!

    = render 'coupons/regend_list'
    = render 'coupons/list'

app/views/coupons/me.html.haml
- content_for :title do
  = "띠부띠부 - #{@user.name}님의 씰 모음"

- content_for :meta do
  %meta{content: "#{@user.name}님은 현재 #{@user.getting_coupons_count(@brand.id)}의 띠부띠부씰을 모았습니다. #{@user.remaining_coupons_count(@brand.id)}의 씰을 모으면 모음이 완성됩니다", name: "description"}
  %meta{content: "띠부띠부, 카카오프렌즈, 씰, 교환, #{@user.cities_name if @user.cities.exists?} #{@user.company.name if @user.company_id.present?} TibuTibu", name: "keyword"}

  %meta{content: "website", property: "og:type"}
  %meta{content: "382538818551395", property: "fb:app_id"}
  %meta{content: "Tibutibu(띠부띠부 자랑)", property: "og:title"}
  %meta{content: user_coupons_url(@user), property: "og:url", rel: "canonical"}
  %meta{content: "총 #{@user.getting_coupons(@brand.id).length} 개 띠부띠부 교환 가능!", property: "og:description"}
  %meta{content: asset_url('ssyls/1.jpg'), property: "og:image"}

.hidden
  %h3= "#{@user.name}님은 현재까지 띠부띠부씰 모음 결과입니다."
  %p= "#{@user.name}님은 #{@user.getting_coupons_count(@brand.id)}의 씰을 모았고, 앞으로 #{@user.remaining_coupons_count(@brand.id)}의 씰을 모으면 컬렉션이 완성됩니다"
  %h4 현재까지 모은 띠부띠부 씰의 번호
  %p= @user_ssyl_ids.join("번, ") + "번"


.row
  #user-detail.col-md-12
    .portfolio-thumnail.text-center
      %a{href: "#"}
        %img.profile-image{alt: "", src: @user.image}
    %ul.text-center.list-inline.list-unstyled
      %li.phone{ class: "#{ 'active' if @user.phone_number.present? and not @user.phone_number.nil? }"}
        - if user_signed_in?
          - if @user.phone_number.start_with?('http')
            %a{href: "#", rel: "popover", target: "_blank", data: {container: "body", toggle: "popover", html: true, placement: "top", content: "#{(@user.phone_number.present? ? "<a href='#{@user.phone_number}'>오픈채팅에 연결하기</a>" : "설정탭에서 오픈채팅(전화번호)를 적어주세요.")}"} }
              %i.fa.fa-mobile
              %span.small 오픈채팅
          - else
            %a{href: "#", rel: "popover", data: {container: "body", toggle: "popover", html: true, placement: "top", content: "#{(@user.phone_number.present? ? "<a href='tel:+#{@user.phone_number}'>#{@user.phone_number}</a>" : "설정탭에서 오픈채팅(전화번호)를 적어주세요.")}"} }
              %i.fa.fa-mobile
              %span.small Phone
        - else
          %a{href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "top", content: "#{(@user.phone_number.present? ? "로그인해야만 볼 수 있습니다." : "전화번호를 등록하지 않았습니다.")}"} }
            %i.fa.fa-mobile
            %span.small Phone

      - if user_signed_in?
        %li.kakao{ class: "#{ 'active' if @user.kakao_id.present? and not @user.kakao_id.nil?}"}
          %a{ href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "bottom", content: "#{(@user.kakao_id.present? ? @user.kakao_id : "설정탭에서 카카오톡 ID를 적어주세요.") }"}}
            %i.fa.fa-comments
            %span.small Kakao ID
      - else
        %li.kakao{ class: "#{ 'active' if @user.kakao_id.present? and not @user.kakao_id.nil?}"}
          %a{ href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "bottom", content: "#{(@user.kakao_id.present? ? "로그인해야만 볼 수 있습니다." : "카카오톡 ID를 등록하지 않았습니다.") }"}}
            %i.fa.fa-comments
            %span.small Kakao ID

      - if user_signed_in?
        - has_cities = @user.cities.exists?
        %li.location{class: "#{'active' if has_cities}"}
          %a{ href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "top", content: "#{(has_cities ? @user.cities_name : "설정탭에서 교환가능 지역을 적어주세요.")}"}}
            %i.fa.fa-location-arrow
            %span.small Location
      - else
        %li.location{class: "#{'active' if @user.cities.exists?}"}
          %a{ href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "top", content: "#{(@user.cities.exists? ? "로그인해야만 볼 수 있습니다." : "장소를 등록하지 않았습니다.")}"}}
            %i.fa.fa-location-arrow
            %span.small Location

      - if user_signed_in?
        - has_group = @user.company && @user.company.name.present?
        %li.group{class: "#{'active' if has_group}"}
          %a{ href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "top", content: "#{(has_group ? @user.company.name : "설정탭에서 교환가능 지역을 적어주세요.")}"}}
            %i.fa.fa-flag
            %span.small Group
      - else
        %li.location{class: "#{'active' if @user.company_id.present?}"}
          %a{ href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "top", content: "#{(@user.company_id.present? ? "로그인해야만 볼 수 있습니다." : "그룹를 등록하지 않았습니다.")}"}}
            %i.fa.fa-flag
            %span.small Group



  %ul.text-right.list-inline.list-unstyled
    .share-wrapper.pull-left
      - if current_user && current_user.provider == 'kakao' && @user == current_user
        %button.btn-xs.btn-default.ssyl.ssyl-xs.kakao#share_kakao_story{ data: { toggle: "modal", target: "#post-kakao-story" } } 카스에 자랑하기
      %button.btn-xs.btn-default.ssyl.ssyl-xs.fb#share_facebook FB에 공유하기

    - if current_user
      %button.btn-xs.btn-default.ssyl.ssyl-xs.exchange Ex
      %span.glyphicon.glyphicon-remove
      - if @user == current_user
        %span= current_user.recommended_coupons_count(@brand.id)
      - else
        %span= current_user.recommended_coupons_count_with(@user, @brand.id)

    %button.btn-xs.btn-default.ssyl.ssyl-xs.active Get
    %span.glyphicon.glyphicon-remove
    %span= @user.getting_coupons_count(@brand.id)

    %button.btn-xs.btn-default.ssyl.ssyl-xs Miss
    %span.glyphicon.glyphicon-remove
    %span= @user.remaining_coupons_count(@brand.id)

  #coupon-list
    - recommended_ssyl_ids = current_user.recommended_coupons(@brand.id).pluck(:tibu_tibu_id) if current_user
    - @tibutibus.each do |tibutibu|
      .col-md-2.col-sm-3.col-xs-4.ssyl-wrapper
        - if @user_ssyl_ids.include? tibutibu.id
          - coupon = @user_coupons.find_by(tibu_tibu_id: tibutibu.id)
          - has_ssyl = (@my_ssyl_ids and @my_ssyl_ids.include?(tibutibu.id))
          - if (coupon.count > 1 and @user != current_user and not has_ssyl)
            = render 'coupons/me/exchange_ssyl', coupon: coupon
          - else
            = render 'coupons/me/active_ssyl', coupon: coupon

        - elsif current_user and recommended_ssyl_ids.include? tibutibu.id
          - if current_user == @user or @user_ssyl_ids.include? tibutibu.id
            = render 'coupons/me/recommended_ssyl', tibutibu: tibutibu
          - else
            = render 'coupons/me/other_user_yet_ssyl', tibutibu: tibutibu

        - elsif current_user == @user
          = render 'coupons/me/create_ssyl', tibutibu: tibutibu

        - else
          = render 'coupons/me/other_user_yet_ssyl', tibutibu: tibutibu


- if current_user
  #update-ssyl.modal.fade{ tabindex: "-1" }
    .modal-dialog
      .modal-content

  - if @user == current_user
    = render 'coupons/story_post_modal'

- if current_user
  #recommend-ssyl.modal.fade{ tabindex: "-1" }
    .modal-dialog
      .modal-content

  #exchange-ssyl.modal.fade{ tabindex: "-1" }
    .modal-dialog
      .modal-content


:javascript
  $('#share_facebook').click(function() {
    window.open("http://facebook.com/sharer.php?u=#{user_coupons_url(@user)}", "TW", "left=0,top=0,toolbar=no,status=no,scrollbars=no,resizeable=no,menubar=no,location=no,width=600,height=500");
  });

app/views/coupons/new.html.haml
= render 'form'

app/views/coupons/recommend.html.haml
.modal-header
  %button.close{type: "button", data: { dismiss: "modal" }}
    %span &times;
    %span.sr-only Close
  %h4.modal-title 씰 교환 가능한 목록 보기

.modal-body
  %h4= "아래 사람들이 #{@tibutibu.num}번 씰을 2개 이상 보유하고 있습니다"
  %ul.list-unstyled.list-inline
    - @recommend_coupons.each do |coupon|
      - user = coupon.user
      - title = "<a href='#{user_coupons_path(user)}'><i class='fa fa-quote-left'></i> #{user.name}님과 교환가능 한 씰</a>"
      - content = exchangerble_ssyls(user.recommended_coupons_with(current_user, @brand.id), user)
      %li
        %button.media-object.profile-image{ style: "background-image:url(#{user.image});", data: { toggle: "popover", title: title, content: content } }
  .clearfix

.modal-footer
  .text-center
    = button_to "나, 이 씰 구했어요!!", {controller: "coupons", action: "create", coupon: {tibu_tibu_id: @tibutibu.id}}, method: :create, class: "btn btn-primary"

:javascript
  $(document).ready(function() {
    $(".profile-image").popover({
      trigger: "click",
      placement: "bottom",
      html: true
    }).on("show.bs.popover", function() {
      $(this).addClass('exchange');
    }).on("hide.bs.popover", function() {
      $(this).removeClass('exchange');
    });
  });

app/views/coupons/request_exchange.html.haml
%form
  .modal-header
    %button.close{type: "button", data: { dismiss: "modal" }}
      %span &times;
      %span.sr-only Close
    %h4.modal-title 씰 교환 가능한 목록 보기

  .modal-body
    %h3= "'#{@user.name}'님과 씰을 교환해보아요."

    .request-coupon.row
      .col-md-12
        %h4
          %i.fa.fa-square
          내가 받는 쿠폰
        .row
          .col-md-12
            .ssyl.exchange{ style: "background-image:url(#{asset_path('ssyls/' + @coupon.tibu_tibu_id.to_s + '.jpg')})"}

    .candidate_coupons.row
      .col-md-12
        %h4
          %i.fa.fa-square
          = "'#{@user.name}'님이 필요한 내 쿠폰"
        - if @candidate_coupons.present?
          .row
            %ul.col-md-12.list-unstyled.list-inline
              - @candidate_coupons.each do |coupon|
                %li
                  %input{ id: "candidate-#{coupon.id}", type: :radio, name: :coupon, value: coupon.id }
                  %label.ssyl{ for: "candidate-#{coupon.id}", style: "background-image: url(#{asset_path('ssyls/' + coupon.tibu_tibu_id.to_s + '.jpg')});" }
        - else
          .alert.alert-warning 교환할 수 있는 쿠폰이 없습니다.

-#
  .modal-footer
    .text-center
      = button_to "우리, 씰 교환해요!!", {controller: :exchange, action: :create}, class: 'btn btn-primary, btn-lg'

app/views/coupons/show.html.haml
.row
  .space-10
  #coupon-detail.col-md-12
    = render 'coupon'

    #loading-recommend-spinner.text-center
      = link_to "Loading...", new_coupon_path, class: 'btn btn-lg new-coupon-btn'
    .space-30
    #coupon-recommend-list
      - if @recommend_coupons.present?
        = render 'recommend_list'