config/routes.rb
Coupan::Application.routes.draw do

  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      :registrations => "registrations"
    }

  root 'home#index'
  resources :brands, only: [:index, :show] do
    resources :coupons, only: [:index]
  end

  resources :coupons # index is legacy url (for above brand_coupon)

  resources :release_notes, only: [:index] do
    collection do
      get 'recent'
    end
  end

  resources :notifications, only: [:index] do
    collection do
      get 'recent'
    end
  end

  get '/brands/:brand_id/users/:id/coupons', to: 'coupons#me', as: 'brand_user_coupons'
  get '/users/:id/coupons', to: 'coupons#me', as: 'user_coupons' # legacy url(for above)

  get '/users/:id/coupons/:tibu_tibu_id/', to: 'coupons#recommend', as: 'recommend_coupons'
  post '/users/:id/coupons/post_kakao_story', to: 'coupons#post_kakao_story', as: 'post_kakao_story'
  get '/users/:id/coupons/:tibu_tibu_id/request_exchange', to: 'coupons#request_exchange', as: 'request_exchange_coupon'

  get '/oauth/', to: 'home#oauth_redirect'

  resource :api do
    member do
      get 'stores'
      get 'companies'
      get '/cities/:province_id/', to: 'apis#cities'
    end
  end

  get '/googlec41459c75d69b2af.html', to: 'home#google_valification'

  resources :coupons

end

app/models/brand.rb
class Brand < ActiveRecord::Base

  has_many :tibu_tibus

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  skip_before_action :authenticate_user!

  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.find(params.fetch(:id, nil))
    session["brand_id"] = @brand.id

    redirect_to brand_coupons_path(@brand.id)
  end

end

app/views/brands/index.html.haml
- content_for :title do
  = "띠부띠부 - 브랜드 선택"

- content_for :meta do
  %meta{content: "띠부띠부 모음 순위 - 현재까지 씰을 모두 모은 사용자는 #{@legend_users.size if @legend_users.present?}명입니다.", name: "description"}
  %meta{content: "띠부띠부, 카카오프렌즈, 씰, 교환, 순위, TibuTibu", name: "keyword"}


#brands.row
  - @brands.each do |brand|
    .col-xs-6.col-sm-4.col-md-3
      = link_to brand_path(brand), class: "thumbnail" do
        = image_tag asset_path("brands/#{brand.image}")
        .caption
          %h6= brand.name