config/routes.rb
Coupan::Application.routes.draw do

  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      :registrations => "registrations"
    }

  root 'home#index'
  resources :brands, only: [:index, :show] do
    resources :coupons, only: [:index]
  end

  resources :coupons # index is legacy url (for above brand_coupon)

  resources :release_notes, only: [:index] do
    collection do
      get 'recent'
    end
  end

  resources :notifications, only: [:index] do
    collection do
      get 'recent'
    end
  end

  get '/brands/:brand_id/users/:id/coupons', to: 'coupons#me', as: 'brand_user_coupons'
  get '/users/:id/coupons', to: 'coupons#me', as: 'user_coupons' # legacy url(for above)

  get '/users/:id/coupons/:tibu_tibu_id/', to: 'coupons#recommend', as: 'recommend_coupons'
  post '/users/:id/coupons/post_kakao_story', to: 'coupons#post_kakao_story', as: 'post_kakao_story'
  get '/users/:id/coupons/:tibu_tibu_id/request_exchange', to: 'coupons#request_exchange', as: 'request_exchange_coupon'

  get '/oauth/', to: 'home#oauth_redirect'

  resource :api do
    member do
      get 'stores'
      get 'companies'
      get '/cities/:province_id/', to: 'apis#cities'
    end
  end

  get '/googlec41459c75d69b2af.html', to: 'home#google_valification'

  resources :coupons

end

app/views/layouts/_alert_user_info_empty.html.haml
- if current_user and current_user.is_empty_info?
  .row.alert-user-info-container
    %a{href: "#{edit_user_registration_path}"}
      .alert.alert-sm.alert-warning
        사용자정보를 입력해주세요~
        %span.glyphicon.glyphicon-chevron-right.pull-right

app/views/layouts/_header.html.haml
- has_notice = (current_user and (current_user.visited_notice.nil? or current_user.visited_notice < ReleaseNote.last_updated_at))

%nav.navbar.navbar-default.navbar-fixed-top.sticky-nav{role: "navigation"}
  .container
    .navbar-header
      = link_to brand_coupons_path(@brand), class: 'navbar-brand' do
        %span.title= 'T.Tibu'
        %span.brand-name= "- #{(@brand.name)}"

    - if current_user
      - if current_user.has_unread_notification
        %a#notification.event.active.pull-right{ data: { url: recent_notifications_path, toggle: "popover", placement: "bottom" } }
          %span.glyphicon.glyphicon-bell
          %span.title Exchangable!
      - else
        %a#notification.event.pull-right{ data: { url: recent_notifications_path, toggle: "popover", placement: "bottom" } }
          %span.glyphicon.glyphicon-bell

      - if has_notice
        %a#notice.active.event.pull-right{ data: { url: recent_release_notes_path, toggle: "popover", placement: "bottom" } }
          %span.glyphicon.glyphicon-exclamation-sign
          %span.title New Stuff!
      - else
        %a#notice.event.pull-right{ href: release_notes_path }
          %span.glyphicon.glyphicon-exclamation-sign

    - elsif controller.controller_name != 'sessions'
      .navbar-collapse{style: "height: 1px;"}
        %ul.nav.navbar-nav.navbar-right
          %li.pull-right
            %a{href: "#{root_path}"} Login

app/views/layouts/_meta.html.haml
/ SEO setting
%meta{content: "Tibutibu(띠부띠부)", name: "Author"}
%meta{content: "띠부띠부씰을 교환하세요", name: "Description"}
%meta{content: "띠부띠부, 카카오, Tibutibu", name: "Keyword"}
%meta{content: "noarchive", name: "robots"}
%meta{content: "xKC9MSkXkoOlnLWFsubV8oZiU-j8TZ7X8PorlGINN5g", name: "google-site-verification"}


/ Facebook og setting
%meta{content: "website", property: "og:type"}
%meta{content: "382538818551395", property: "fb:app_id"}
%meta{content: "Tibutibu(띠부띠부)", property: "og:title"}
%meta{content: "http://tibutibu.coupan.so/", property: "og:url", rel: "canonical"}
%meta{content: "띠부띠부씰을 교환하세요", property: "og:description"}

-#
  / og image tags
  %meta{content: "https://lingring.net/static/image/logoFBOG_1.png", property: "og:image"}
  %meta{content: "image/png", property: "og:image:type"}
  %meta{content: "200", property: "og:image:width"}
  %meta{content: "200", property: "og:image:height"}

app/views/layouts/_nav.html.haml
- if current_user
  %nav.navbar.navbar-default.navbar-fixed-bottom{role: "navigation"}
    .container
      .row
        %ul.list-unstyled.list-inline.text-center
          %li.col-xs-3{ class: "#{'active' if controller.controller_name == 'brands'}"}
            %a{href: "#{brands_path}"}
              %i.fa.fa-exchange
              %span.help-text 브랜드
          %li.col-xs-3{ class: "#{'active' if controller.controller_name == 'coupons' and controller.action_name == 'index' }"}
            %a{href: "#{brand_coupons_path(@brand.id)}"}
              %i.fa.fa-list
              %span.help-text 띠부띠부랭크
          %li.col-xs-3{ class: "#{'active' if (controller.controller_name == 'coupons' and controller.action_name == 'me' and @user == current_user) }"}
            %a{href: "#{brand_user_coupons_path(@brand.id, current_user.id)}"}
              %i.fa.fa-user
              %span.help-text 내 씰
          %li.col-xs-3{ class: "#{'active' if controller.controller_name == 'registrations'}"}
            %a{href: "#{edit_user_registration_path}"}
              %i.fa.fa-ellipsis-h
              %span.help-text 설정

- else
  %nav.navbar.navbar-default.navbar-fixed-bottom{role: "navigation"}
    .container
      .row
        %ul.list-unstyled.list-inline.text-center
          %li.col-xs-6{ class: "#{'active' if controller.controller_name == 'brands'}"}
            %a{href: "#{brands_path}"}
              %i.fa.fa-exchange
              %span.help-text 브랜드
          %li.col-xs-6{ class: "#{'active' if controller.controller_name == 'coupons' and controller.action_name == 'index' }"}
            %a{href: "#{brand_coupons_path(@brand.id)}"}
              %i.fa.fa-list
              %span.help-text 띠부띠부랭크

app/views/layouts/_spinner.html.haml
.spinner
  .rect1
  .rect2
  .rect3
  .rect4
  .rect5

app/views/layouts/_toast.html.haml
#toast.alert.alert-dismissible
  %span.message
  %button.close{ type: :button, data: { dismiss: "alert" } } &times;

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui"}
    %meta{content: "띠부띠부 모음", name: "description"}
    %meta{content: "띠부띠부, 카카오프렌즈, 씰, 교환, 순위, TibuTibu", name: "keyword"}
    %meta{ name: "apple-mobile-web-app-capable", content: "yes" }

    %link{href: asset_path("favicons/apple-touch-icon-57x57.png"), rel: "apple-touch-icon", sizes: "57x57"}
    %link{href: asset_path("favicons/apple-touch-icon-114x114.png"), rel: "apple-touch-icon", sizes: "114x114"}
    %link{href: asset_path("favicons/apple-touch-icon-72x72.png"), rel: "apple-touch-icon", sizes: "72x72"}
    %link{href: asset_path("favicons/apple-touch-icon-60x60.png"), rel: "apple-touch-icon", sizes: "60x60"}
    %link{href: asset_path("favicons/apple-touch-icon-120x120.png"), rel: "apple-touch-icon", sizes: "120x120"}
    %link{href: asset_path("favicons/apple-touch-icon-76x76.png"), rel: "apple-touch-icon", sizes: "76x76"}
    %link{href: asset_path("favicons/favicon-96x96.png"), rel: "icon", sizes: "96x96", type: "image/png"}
    %link{href: asset_path("favicons/favicon-16x16.png"), rel: "icon", sizes: "16x16", type: "image/png"}
    %link{href: asset_path("favicons/favicon-32x32.png"), rel: "icon", sizes: "32x32", type: "image/png"}
    %meta{content: "#da532c", name: "msapplication-TileColor"}

    = content_for?(:meta) ? yield(:meta) : (render 'layouts/meta')
    %title= content_for?(:title) ? yield(:title) : "띠부띠부 (TibuTibu)"
    = stylesheet_link_tag 'font-awesome'
    = stylesheet_link_tag 'application'

    %link{href: "http://fonts.googleapis.com/css?family=Raleway:400,300,100,700,800,500", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Playfair+Display:400italic", rel: "stylesheet", type: "text/css"}
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>]
    = stylesheet_link_tag params[:controller]
    = yield :page_specific_stylesheets


    = javascript_include_tag 'application'
    = yield :page_specific_head_scripts
    = javascript_include_tag params[:controller]

    = csrf_meta_tags

  %body
    = render "layouts/header"

    /
      <haml_loud> link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) </haml_loud>

    #content.container
      .col-xs-12
        = render 'layouts/alert_user_info_empty'
        .row
          = content_for?(:contents) ? yield(:contents) : yield

    = render "layouts/nav"
    = render "layouts/spinner"
    = render "layouts/toast"

    = yield :page_specific_scripts